This is makeindex, version 2.15 [TeX Live 2012] (kpathsea + Thai support).
Scanning style file ./libroResonancia.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file libroResonancia.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file libroResonancia.acr....done (6 lines written, 0 warnings).
Output written in libroResonancia.acr.
Transcript written in libroResonancia.alg.
